name = input("Enter Emp Name")
Empid = int(input("Enter Emp ID :"))
Empdes = input("Enter Designation:")
Empdoj = input("Enter DOJ mm/dd/yyyy:")
Empsal = float(input("Enter the Salary"))

print("#"*40)
print("Empoloyee Profile")
print("#"*40)
print("Employee Name",name)
print("Employee ID",Empid)
print("Employee Designation",Empdes)
print("Employee DOJ",Empdoj)
print("Employee Salary",Empsal)
